changelog:
  categories:
    - title: "Removed / Breaking changes"
      labels:
        - "breaking-change"
    - title: "Added"
      labels:
        - "enhancement"
    - title: "Fixed"
      labels:
        - "bug"
        - "security"
    - title: "Changed"
      labels:
        - "documentation"
        - "refactor"
    - title: "Other changes"
      labels:
        - "*"
      exclude:
        labels:
          - "breaking-change"
          - "enhancement"
          - "bug"
          - "security"
          - "documentation"
          - "refactor"
